name: Bug report
description: Report an error or unexpected behavior
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        You can share a Quarto document using the following syntax:

            ````qmd
            ---
            title: "Reproducible Quarto Document"
            format: html
            engine: jupyter
            ---
            
            This is a reproducible Quarto document using `format: html`.
            It is written in Markdown and contains embedded Python code.
            When you run the code, it will produce a message.
            
            ```{python}
            print("Hello, world!")
            ```
            
            ![An image]({{< placeholder 600 400 >}}){#fig-placeholder}
            
            {{< lipsum 1 >}}
            
            A reference to @fig-placeholder.
            
            The end.
            ````

  - type: input
    id: name
    attributes:
      label: First name